name: Deploy Dist
# on: [push, workflow_dispatch]

on:
  push:
      branches:
      - main
      - 'feature/**'
      paths-ignore:
        - '.github/workflows/*'
        - README.md
  workflow_dispatch:      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
        # run: |
        #   echo "Cloning repo..."
        #   echo "${{toJson(github)}}"
        #   git clone https://github.com/${{github.repository}}.git
      - name: Install Nodejs 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache Depedencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          # ubuntu-node-23
          key: ${{ runner.os }}-node-${{hashFiles('**/package-lock.json')}}
      - name: print node version
        run: node -v
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Nodejs 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache Depedencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          # ubuntu-node-23
          key: ${{ runner.os }}-node-${{hashFiles('**/package-lock.json')}}
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo "Deploy successfull"
